/*
 * Copyright 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.jetcaster.designsystem.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFFF792C)
val onPrimaryLight = Color(0xFF626004)
val primaryContainerLight = Color(0xFF313002)
val onPrimaryContainerLight = Color(0xFFFDFCCE)
val secondaryLight = Color(0xFFFFE523)
val onSecondaryLight = Color(0xFF332D00)
val secondaryContainerLight = Color(0xFF998700)
val onSecondaryContainerLight = Color(0xFFFFF9CC)
val tertiaryLight = Color(0xFFFF9AD8)
val onTertiaryLight = Color(0xFF33000A)
val tertiaryContainerLight = Color(0xFF660014)
val onTertiaryContainerLight = Color(0xFF663600)
val errorLight = Color(0xFFFFE5EB)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFEF7FF)
val onBackgroundLight = Color(0xFF1D1B20)
val surfaceLight = Color(0xFFFEF7FF)
val onSurfaceLight = Color(0xFF1D1B20)
val surfaceVariantLight = Color(0xFFE7E0EB)
val onSurfaceVariantLight = Color(0xFF49454E)
val outlineLight = Color(0xFF7A757F)
val outlineVariantLight = Color(0xFFCBC4CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFFEFE0D6)
val inverseOnSurfaceLight = Color(0xFF382F28)
val inversePrimaryLight = Color(0xFFD3BCFD)
val surfaceDimLight = Color(0xFF19120C)
val surfaceBrightLight = Color(0xFF413731)
val surfaceContainerLowestLight = Color(0xFF140D08)
val surfaceContainerLowLight = Color(0xFF221A14)
val surfaceContainerLight = Color(0xFF261E18)
val surfaceContainerHighLight = Color(0xFF312822)
val surfaceContainerHighestLight = Color(0xFF3C332C)

val primaryLightMediumContrast = Color(0xFFFF792C)
val onPrimaryLightMediumContrast = Color(0xFF626004)
val primaryContainerLightMediumContrast = Color(0xFF313002)
val onPrimaryContainerLightMediumContrast = Color(0xFFFDFCCE)
val secondaryLightMediumContrast = Color(0xFFFFE523)
val onSecondaryLightMediumContrast = Color(0xFF332D00)
val secondaryContainerLightMediumContrast = Color(0xFF998700)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFF9CC)
val tertiaryLightMediumContrast = Color(0xFFFF9AD8)
val onTertiaryLightMediumContrast = Color(0xFF33000A)
val tertiaryContainerLightMediumContrast = Color(0xFF660014)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFE5EB)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFEF7FF)
val onBackgroundLightMediumContrast = Color(0xFF1D1B20)
val surfaceLightMediumContrast = Color(0xFFFEF7FF)
val onSurfaceLightMediumContrast = Color(0xFF121016)
val surfaceVariantLightMediumContrast = Color(0xFFE7E0EB)
val onSurfaceVariantLightMediumContrast = Color(0xFF38353D)
val outlineLightMediumContrast = Color(0xFF55515A)
val outlineVariantLightMediumContrast = Color(0xFF706B75)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF322F35)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF5EFF7)
val inversePrimaryLightMediumContrast = Color(0xFFD3BCFD)
val surfaceDimLightMediumContrast = Color(0xFF19120C)
val surfaceBrightLightMediumContrast = Color(0xFF413731)
val surfaceContainerLowestLightMediumContrast = Color(0xFF140D08)
val surfaceContainerLowLightMediumContrast = Color(0xFF221A14)
val surfaceContainerLightMediumContrast = Color(0xFF261E18)
val surfaceContainerHighLightMediumContrast = Color(0xFF312822)
val surfaceContainerHighestLightMediumContrast = Color(0xFF3C332C)

val primaryLightHighContrast = Color(0xFF342157)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF523F77)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF30293C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF4D465A)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF45212C)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF673D48)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFEF7FF)
val onBackgroundLightHighContrast = Color(0xFF1D1B20)
val surfaceLightHighContrast = Color(0xFFFEF7FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE7E0EB)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2E2B33)
val outlineVariantLightHighContrast = Color(0xFF4C4751)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF322F35)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFD3BCFD)
val surfaceDimLightHighContrast = Color(0xFFBCB7BF)
val surfaceBrightLightHighContrast = Color(0xFFFEF7FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF5EFF7)
val surfaceContainerLightHighContrast = Color(0xFFE7E0E8)
val surfaceContainerHighLightHighContrast = Color(0xFFD8D2DA)
val surfaceContainerHighestLightHighContrast = Color(0xFFCAC4CC)

val primaryDark = Color(0xFFF0FCB0)
val onPrimaryDark = Color(0xFF626004)
val primaryContainerDark = Color(0xFF313002)
val onPrimaryContainerDark = Color(0xFFFDFCCE)
val secondaryDark = Color(0xFFFFE523)
val onSecondaryDark = Color(0xFF332D00)
val secondaryContainerDark = Color(0xFF998700)
val onSecondaryContainerDark = Color(0xFFFFF9CC)
val tertiaryDark = Color(0xFFFF9AD8)
val onTertiaryDark = Color(0xFF33000A)
val tertiaryContainerDark = Color(0xFF660014)
val onTertiaryContainerDark = Color(0xFFFFE5EB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF151218)
val onBackgroundDark = Color(0xFFE7E0E8)
val surfaceDark = Color(0xFF261604)
val onSurfaceDark = Color(0xFFFBEDE4)
val surfaceVariantDark = Color(0xFF49454E)
val onSurfaceVariantDark = Color(0xFFCBC4CF)
val outlineDark = Color(0xFF948F99)
val outlineVariantDark = Color(0xFF49454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E0E8)
val inverseOnSurfaceDark = Color(0xFF322F35)
val inversePrimaryDark = Color(0xFF68548E)
val surfaceDimDark = Color(0xFF19120C)
val surfaceBrightDark = Color(0xFF413731)
val surfaceContainerLowestDark = Color(0xFF140D08)
val surfaceContainerLowDark = Color(0xFF221A14)
val surfaceContainerDark = Color(0xFF261E18)
val surfaceContainerHighDark = Color(0xFF312822)
val surfaceContainerHighestDark = Color(0xFF3C332C)

val primaryDarkMediumContrast = Color(0xFFF0FCB0)
val onPrimaryDarkMediumContrast = Color(0xFF626004)
val primaryContainerDarkMediumContrast = Color(0xFF313002)
val onPrimaryContainerDarkMediumContrast = Color(0xFFFDFCCE)
val secondaryDarkMediumContrast = Color(0xFFFFE523)
val onSecondaryDarkMediumContrast = Color(0xFF332D00)
val secondaryContainerDarkMediumContrast = Color(0xFF998700)
val onSecondaryContainerDarkMediumContrast = Color(0xFFFFF9CC)
val tertiaryDarkMediumContrast = Color(0xFFFF9AD8)
val onTertiaryDarkMediumContrast = Color(0xFF33000A)
val tertiaryContainerDarkMediumContrast = Color(0xFF660014)
val onTertiaryContainerDarkMediumContrast = Color(0xFFFFE5EB)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF151218)
val onBackgroundDarkMediumContrast = Color(0xFFE7E0E8)
val surfaceDarkMediumContrast = Color(0xFF151218)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF49454E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE1DAE5)
val outlineDarkMediumContrast = Color(0xFFB6B0BA)
val outlineVariantDarkMediumContrast = Color(0xFF948E98)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE7E0E8)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF322F35)
val inversePrimaryDarkMediumContrast = Color(0xFF68548E)
val surfaceDimDarkMediumContrast = Color(0xFF19120C)
val surfaceBrightDarkMediumContrast = Color(0xFF413731)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF140D08)
val surfaceContainerLowDarkMediumContrast = Color(0xFF221A14)
val surfaceContainerDarkMediumContrast = Color(0xFF261E18)
val surfaceContainerHighDarkMediumContrast = Color(0xFF312822)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C332C)

val primaryDarkHighContrast = Color(0xFFF0FCB0)
val onPrimaryDarkHighContrast = Color(0xFF626004)
val primaryContainerDarkHighContrast = Color(0xFF313002)
val onPrimaryContainerDarkHighContrast = Color(0xFFFDFCCE)
val secondaryDarkHighContrast = Color(0xFFFFE523)
val onSecondaryDarkHighContrast = Color(0xFF332D00)
val secondaryContainerDarkHighContrast = Color(0xFF998700)
val onSecondaryContainerDarkHighContrast = Color(0xFFFFF9CC)
val tertiaryDarkHighContrast = Color(0xFFFF9AD8)
val onTertiaryDarkHighContrast = Color(0xFF33000A)
val tertiaryContainerDarkHighContrast = Color(0xFF660014)
val onTertiaryContainerDarkHighContrast = Color(0xFFFFE5EB)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF151218)
val onBackgroundDarkHighContrast = Color(0xFFE7E0E8)
val surfaceDarkHighContrast = Color(0xFF151218)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF49454E)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF5EDF9)
val outlineVariantDarkHighContrast = Color(0xFFC7C0CB)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE7E0E8)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF513E75)
val surfaceDimDarkHighContrast = Color(0xFF19120C)
val surfaceBrightDarkHighContrast = Color(0xFF413731)
val surfaceContainerLowestDarkHighContrast = Color(0xFF140D08)
val surfaceContainerLowDarkHighContrast = Color(0xFF221A14)
val surfaceContainerDarkHighContrast = Color(0xFF261E18)
val surfaceContainerHighDarkHighContrast = Color(0xFF312822)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3C332C)
