/*
 * Copyright 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.jetcaster.designsystem.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFFF792C)
val onPrimaryLight = Color(0xFFFFECE0)
val primaryContainerLight = Color(0xFFFFDBCC)
val onPrimaryContainerLight = Color(0xFF662500)
val secondaryLight = Color(0xFFFFBD1D)
val onSecondaryLight = Color(0xFF664800)
val secondaryContainerLight = Color(0xFFFFEECC)
val onSecondaryContainerLight = Color(0xFF664800)
val tertiaryLight = Color(0xFFFF8F0F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFE5CC)
val onTertiaryContainerLight = Color(0xFF663600)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFEF7FF)
val onBackgroundLight = Color(0xFF1D1B20)
val surfaceLight = Color(0xFFFEF7FF)
val onSurfaceLight = Color(0xFF1D1B20)
val surfaceVariantLight = Color(0xFFE7E0EB)
val onSurfaceVariantLight = Color(0xFF49454E)
val outlineLight = Color(0xFF7A757F)
val outlineVariantLight = Color(0xFFCBC4CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F35)
val inverseOnSurfaceLight = Color(0xFFF5EFF7)
val inversePrimaryLight = Color(0xFFD3BCFD)
val surfaceDimLight = Color(0xFFDED8E0)
val surfaceBrightLight = Color(0xFFFEF7FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F1FA)
val surfaceContainerLight = Color(0xFFF2ECF4)
val surfaceContainerHighLight = Color(0xFFEDE6EE)
val surfaceContainerHighestLight = Color(0xFFE7E0E8)

val primaryLightMediumContrast = Color(0xFF3E2C62)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF77639D)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF3A3346)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF72697F)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF512A36)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF8F606C)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFEF7FF)
val onBackgroundLightMediumContrast = Color(0xFF1D1B20)
val surfaceLightMediumContrast = Color(0xFFFEF7FF)
val onSurfaceLightMediumContrast = Color(0xFF121016)
val surfaceVariantLightMediumContrast = Color(0xFFE7E0EB)
val onSurfaceVariantLightMediumContrast = Color(0xFF38353D)
val outlineLightMediumContrast = Color(0xFF55515A)
val outlineVariantLightMediumContrast = Color(0xFF706B75)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF322F35)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF5EFF7)
val inversePrimaryLightMediumContrast = Color(0xFFD3BCFD)
val surfaceDimLightMediumContrast = Color(0xFFCAC4CC)
val surfaceBrightLightMediumContrast = Color(0xFFFEF7FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF8F1FA)
val surfaceContainerLightMediumContrast = Color(0xFFEDE6EE)
val surfaceContainerHighLightMediumContrast = Color(0xFFE1DBE3)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD6D0D7)

val primaryLightHighContrast = Color(0xFF342157)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF523F77)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF30293C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF4D465A)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF45212C)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF673D48)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFEF7FF)
val onBackgroundLightHighContrast = Color(0xFF1D1B20)
val surfaceLightHighContrast = Color(0xFFFEF7FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE7E0EB)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2E2B33)
val outlineVariantLightHighContrast = Color(0xFF4C4751)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF322F35)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFD3BCFD)
val surfaceDimLightHighContrast = Color(0xFFBCB7BF)
val surfaceBrightLightHighContrast = Color(0xFFFEF7FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF5EFF7)
val surfaceContainerLightHighContrast = Color(0xFFE7E0E8)
val surfaceContainerHighLightHighContrast = Color(0xFFD8D2DA)
val surfaceContainerHighestLightHighContrast = Color(0xFFCAC4CC)

val primaryDark = Color(0xFFFF792C)
val onPrimaryDark = Color(0xFFFFECE0)
val primaryContainerDark = Color(0xFF703717)
val onPrimaryContainerDark = Color(0xFFFFDBCC)
val secondaryDark = Color(0xFFFFBD1D)
val onSecondaryDark = Color(0xFF412D00)
val secondaryContainerDark = Color(0xFFF0C470)
val onSecondaryContainerDark = Color(0xFF704700)
val tertiaryDark = Color(0xFFFF8F0F)
val onTertiaryDark = Color(0xFF663600)
val tertiaryContainerDark = Color(0xFF6C3A06)
val onTertiaryContainerDark = Color(0xFFFFDCC2)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF151218)
val onBackgroundDark = Color(0xFFE7E0E8)
val surfaceDark = Color(0xFF151218)
val onSurfaceDark = Color(0xFFE7E0E8)
val surfaceVariantDark = Color(0xFF49454E)
val onSurfaceVariantDark = Color(0xFFCBC4CF)
val outlineDark = Color(0xFF948F99)
val outlineVariantDark = Color(0xFF49454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E0E8)
val inverseOnSurfaceDark = Color(0xFF322F35)
val inversePrimaryDark = Color(0xFF68548E)
val surfaceDimDark = Color(0xFF19120C)
val surfaceBrightDark = Color(0xFF413731)
val surfaceContainerLowestDark = Color(0xFF140D08)
val surfaceContainerLowDark = Color(0xFF221A14)
val surfaceContainerDark = Color(0xFF261E18)
val surfaceContainerHighDark = Color(0xFF312822)
val surfaceContainerHighestDark = Color(0xFF3C332C)

val primaryDarkMediumContrast = Color(0xFFFDB186)
val onPrimaryDarkMediumContrast = Color(0xFF2C0C00)
val primaryContainerDarkMediumContrast = Color(0xFFC97E59)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFF0C470)
val onSecondaryDarkMediumContrast = Color(0xFF201400)
val secondaryContainerDarkMediumContrast = Color(0xFFB18B3D)
val onSecondaryContainerDarkMediumContrast = Color(0xFF664800)
val tertiaryDarkMediumContrast = Color(0xFFFFBD87)
val onTertiaryDarkMediumContrast = Color(0xFF663600)
val tertiaryContainerDarkMediumContrast = Color(0xFFC3824A)
val onTertiaryContainerDarkMediumContrast = Color(0xFF663600)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF151218)
val onBackgroundDarkMediumContrast = Color(0xFFE7E0E8)
val surfaceDarkMediumContrast = Color(0xFF151218)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF49454E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE1DAE5)
val outlineDarkMediumContrast = Color(0xFFB6B0BA)
val outlineVariantDarkMediumContrast = Color(0xFF948E98)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE7E0E8)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2C292F)
val inversePrimaryDarkMediumContrast = Color(0xFF513E75)
val surfaceDimDarkMediumContrast = Color(0xFF19120C)
val surfaceBrightDarkMediumContrast = Color(0xFF413731)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF140D08)
val surfaceContainerLowDarkMediumContrast = Color(0xFF221A14)
val surfaceContainerDarkMediumContrast = Color(0xFF261E18)
val surfaceContainerHighDarkMediumContrast = Color(0xFF312822)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C332C)

val primaryDarkHighContrast = Color(0xFFFFF9F8)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFBC9C)
val onPrimaryContainerDarkHighContrast = Color(0xFF662500)
val secondaryDarkHighContrast = Color(0xFFFFFAF7)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFF0C470)
val onSecondaryContainerDarkHighContrast = Color(0xFF664800)
val tertiaryDarkHighContrast = Color(0xFFFFE5CC)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFBD87)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF151218)
val onBackgroundDarkHighContrast = Color(0xFFE7E0E8)
val surfaceDarkHighContrast = Color(0xFF151218)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF49454E)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF5EDF9)
val outlineVariantDarkHighContrast = Color(0xFFC7C0CB)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE7E0E8)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF513E75)
val surfaceDimDarkHighContrast = Color(0xFF19120C)
val surfaceBrightDarkHighContrast = Color(0xFF413731)
val surfaceContainerLowestDarkHighContrast = Color(0xFF140D08)
val surfaceContainerLowDarkHighContrast = Color(0xFF221A14)
val surfaceContainerDarkHighContrast = Color(0xFF261E18)
val surfaceContainerHighDarkHighContrast = Color(0xFF312822)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3C332C)
