{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.constraintlayout",
    "module": "constraintlayout-compose",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ggs4fys42femzj3et27faf3lem"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-compose-1.0.0-SNAPSHOT.aar",
          "url": "constraintlayout-compose-1.0.0-SNAPSHOT.aar",
          "size": 132373,
          "sha512": "2c2f12b5d2954eeda0c3f3903fd5b99e49535a8b4e7842df3736852724c1ebb697cf3aea28564617ab9f7b55ed53e606bfc283accf036c488da098ac21b098b8",
          "sha256": "5a5bb10f041cd63f27f0a7c4881ad76ecebae39b3626f773b78ba654c766d100",
          "sha1": "0c7cfc79fb6166b5343ca2d679cd2f805de10020",
          "md5": "8302f4308bbee1f6aaceca2642286c12"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-core",
          "version": {
            "requires": "1.0.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-compose-1.0.0-SNAPSHOT.aar",
          "url": "constraintlayout-compose-1.0.0-SNAPSHOT.aar",
          "size": 132373,
          "sha512": "2c2f12b5d2954eeda0c3f3903fd5b99e49535a8b4e7842df3736852724c1ebb697cf3aea28564617ab9f7b55ed53e606bfc283accf036c488da098ac21b098b8",
          "sha256": "5a5bb10f041cd63f27f0a7c4881ad76ecebae39b3626f773b78ba654c766d100",
          "sha1": "0c7cfc79fb6166b5343ca2d679cd2f805de10020",
          "md5": "8302f4308bbee1f6aaceca2642286c12"
        }
      ]
    }
  ]
}
