/*
 * Copyright 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.jetcaster.designsystem.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF885200)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFAC46)
val onPrimaryContainerLight = Color(0xFF482900)
val secondaryLight = Color(0xFF7A5817)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFD798)
val onSecondaryContainerLight = Color(0xFF5C3F00)
val tertiaryLight = Color(0xFF994700)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFF801F)
val onTertiaryContainerLight = Color(0xFF2D1000)
val errorLight = Color(0xFFA4384A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFF87889)
val onErrorContainerLight = Color(0xFF32000A)
val backgroundLight = Color(0xFFFFF8F4)
val onBackgroundLight = Color(0xFF221A11)
val surfaceLight = Color(0xFFFFF8F4)
val onSurfaceLight = Color(0xFF221A11)
val surfaceVariantLight = Color(0xFFF7DEC8)
val onSurfaceVariantLight = Color(0xFF544434)
val outlineLight = Color(0xFF877461)
val outlineVariantLight = Color(0xFFDAC3AD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382F25)
val inverseOnSurfaceLight = Color(0xFFFFEEDF)
val inversePrimaryLight = Color(0xFFFFB868)
val surfaceDimLight = Color(0xFFE8D7C9)
val surfaceBrightLight = Color(0xFFFFF8F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E6)
val surfaceContainerLight = Color(0xFFFCEBDC)
val surfaceContainerHighLight = Color(0xFFF6E5D7)
val surfaceContainerHighestLight = Color(0xFFF1E0D1)

val primaryLightMediumContrast = Color(0xFF623A00)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFA76600)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF5A3D00)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF936E2B)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF6F3100)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFBC5800)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF7F1B30)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFC14E5F)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F4)
val onBackgroundLightMediumContrast = Color(0xFF221A11)
val surfaceLightMediumContrast = Color(0xFFFFF8F4)
val onSurfaceLightMediumContrast = Color(0xFF221A11)
val surfaceVariantLightMediumContrast = Color(0xFFF7DEC8)
val onSurfaceVariantLightMediumContrast = Color(0xFF504030)
val outlineLightMediumContrast = Color(0xFF6E5C4A)
val outlineVariantLightMediumContrast = Color(0xFF8B7765)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF382F25)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEEDF)
val inversePrimaryLightMediumContrast = Color(0xFFFFB868)
val surfaceDimLightMediumContrast = Color(0xFFE8D7C9)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F4)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF1E6)
val surfaceContainerLightMediumContrast = Color(0xFFFCEBDC)
val surfaceContainerHighLightMediumContrast = Color(0xFFF6E5D7)
val surfaceContainerHighestLightMediumContrast = Color(0xFFF1E0D1)

val primaryLightHighContrast = Color(0xFF351D00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF623A00)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF301F00)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF5A3D00)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF3C1800)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF6F3100)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4C0014)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF7F1B30)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F4)
val onBackgroundLightHighContrast = Color(0xFF221A11)
val surfaceLightHighContrast = Color(0xFFFFF8F4)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF7DEC8)
val onSurfaceVariantLightHighContrast = Color(0xFF2E2113)
val outlineLightHighContrast = Color(0xFF504030)
val outlineVariantLightHighContrast = Color(0xFF504030)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF382F25)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFE8D4)
val surfaceDimLightHighContrast = Color(0xFFE8D7C9)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F4)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFFF1E6)
val surfaceContainerLightHighContrast = Color(0xFFFCEBDC)
val surfaceContainerHighLightHighContrast = Color(0xFFF6E5D7)
val surfaceContainerHighestLightHighContrast = Color(0xFFF1E0D1)

val primaryDark = Color(0xFFFFCF9E)
val onPrimaryDark = Color(0xFF482900)
val primaryContainerDark = Color(0xFFF79900)
val onPrimaryContainerDark = Color(0xFF371E00)
val secondaryDark = Color(0xFFFFFEFF)
val onSecondaryDark = Color(0xFF422C00)
val secondaryContainerDark = Color(0xFFFBCC80)
val onSecondaryContainerDark = Color(0xFF553A00)
val tertiaryDark = Color(0xFFFFB68B)
val onTertiaryDark = Color(0xFF522300)
val tertiaryContainerDark = Color(0xFFE76E00)
val onTertiaryContainerDark = Color(0xFF000000)
val errorDark = Color(0xFFFFB2B9)
val onErrorDark = Color(0xFF65041F)
val errorContainerDark = Color(0xFFC14E5F)
val onErrorContainerDark = Color(0xFFFFFFFF)
val backgroundDark = Color(0xFF1A120A)
val onBackgroundDark = Color(0xFFF1E0D1)
val surfaceDark = Color(0xFF1A120A)
val onSurfaceDark = Color(0xFFF1E0D1)
val surfaceVariantDark = Color(0xFF544434)
val onSurfaceVariantDark = Color(0xFFDAC3AD)
val outlineDark = Color(0xFFA28D7A)
val outlineVariantDark = Color(0xFF544434)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF1E0D1)
val inverseOnSurfaceDark = Color(0xFF382F25)
val inversePrimaryDark = Color(0xFF885200)
val surfaceDimDark = Color(0xFF1A120A)
val surfaceBrightDark = Color(0xFF42372D)
val surfaceContainerLowestDark = Color(0xFF140D06)
val surfaceContainerLowDark = Color(0xFF221A11)
val surfaceContainerDark = Color(0xFF271E15)
val surfaceContainerHighDark = Color(0xFF32281F)
val surfaceContainerHighestDark = Color(0xFF3D3329)

val primaryDarkMediumContrast = Color(0xFFFFCF9E)
val onPrimaryDarkMediumContrast = Color(0xFF351D00)
val primaryContainerDarkMediumContrast = Color(0xFFF79900)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFFEFF)
val onSecondaryDarkMediumContrast = Color(0xFF422C00)
val secondaryContainerDarkMediumContrast = Color(0xFFFBCC80)
val onSecondaryContainerDarkMediumContrast = Color(0xFF2C1C00)
val tertiaryDarkMediumContrast = Color(0xFFFFBC95)
val onTertiaryDarkMediumContrast = Color(0xFF2A0E00)
val tertiaryContainerDarkMediumContrast = Color(0xFFE76E00)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFB8BE)
val onErrorDarkMediumContrast = Color(0xFF36000C)
val errorContainerDarkMediumContrast = Color(0xFFE5697A)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF1A120A)
val onBackgroundDarkMediumContrast = Color(0xFFF1E0D1)
val surfaceDarkMediumContrast = Color(0xFF1A120A)
val onSurfaceDarkMediumContrast = Color(0xFFFFFAF8)
val surfaceVariantDarkMediumContrast = Color(0xFF544434)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDEC7B1)
val outlineDarkMediumContrast = Color(0xFFB59F8B)
val outlineVariantDarkMediumContrast = Color(0xFF93806D)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFF1E0D1)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF32281F)
val inversePrimaryDarkMediumContrast = Color(0xFF693E00)
val surfaceDimDarkMediumContrast = Color(0xFF1A120A)
val surfaceBrightDarkMediumContrast = Color(0xFF42372D)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF140D06)
val surfaceContainerLowDarkMediumContrast = Color(0xFF221A11)
val surfaceContainerDarkMediumContrast = Color(0xFF271E15)
val surfaceContainerHighDarkMediumContrast = Color(0xFF32281F)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3D3329)

val primaryDarkHighContrast = Color(0xFFFFFAF8)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFBE76)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFFEFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFFBCC80)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFFAF8)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFBC95)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFB8BE)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF1A120A)
val onBackgroundDarkHighContrast = Color(0xFFF1E0D1)
val surfaceDarkHighContrast = Color(0xFF1A120A)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF544434)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFAF8)
val outlineDarkHighContrast = Color(0xFFDEC7B1)
val outlineVariantDarkHighContrast = Color(0xFFDEC7B1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFF1E0D1)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF3F2400)
val surfaceDimDarkHighContrast = Color(0xFF1A120A)
val surfaceBrightDarkHighContrast = Color(0xFF42372D)
val surfaceContainerLowestDarkHighContrast = Color(0xFF140D06)
val surfaceContainerLowDarkHighContrast = Color(0xFF221A11)
val surfaceContainerDarkHighContrast = Color(0xFF271E15)
val surfaceContainerHighDarkHighContrast = Color(0xFF32281F)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3D3329)
