/*
 * Copyright 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.reply.ui.theme
import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val primaryLight = Color(0xFF805610)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDDB3)
val onPrimaryContainerLight = Color(0xFF291800)
val secondaryLight = Color(0xFF6F5B40)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFBDEBC)
val onSecondaryContainerLight = Color(0xFF271904)
val tertiaryLight = Color(0xFF51643F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD4EABB)
val onTertiaryContainerLight = Color(0xFF102004)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F4)
val onBackgroundLight = Color(0xFF201B13)
val surfaceLight = Color(0xFFFFF8F4)
val onSurfaceLight = Color(0xFF201B13)
val surfaceVariantLight = Color(0xFFF0E0CF)
val onSurfaceVariantLight = Color(0xFF4F4539)
val outlineLight = Color(0xFF817567)
val outlineVariantLight = Color(0xFFD3C4B4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF362F27)
val inverseOnSurfaceLight = Color(0xFFFCEFE2)
val inversePrimaryLight = Color(0xFFF4BD6F)
val surfaceDimLight = Color(0xFFE4D8CC)
val surfaceBrightLight = Color(0xFFFFF8F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E5)
val surfaceContainerLight = Color(0xFFF9ECDF)
val surfaceContainerHighLight = Color(0xFFF3E6DA)
val surfaceContainerHighestLight = Color(0xFFEDE0D4)

val primaryLightMediumContrast = Color(0xFF5D3C00)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF996C26)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF524027)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF877155)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF364826)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF677B54)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F4)
val onBackgroundLightMediumContrast = Color(0xFF201B13)
val surfaceLightMediumContrast = Color(0xFFFFF8F4)
val onSurfaceLightMediumContrast = Color(0xFF201B13)
val surfaceVariantLightMediumContrast = Color(0xFFF0E0CF)
val onSurfaceVariantLightMediumContrast = Color(0xFF4B4135)
val outlineLightMediumContrast = Color(0xFF685D50)
val outlineVariantLightMediumContrast = Color(0xFF85796B)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF362F27)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFCEFE2)
val inversePrimaryLightMediumContrast = Color(0xFFF4BD6F)
val surfaceDimLightMediumContrast = Color(0xFFE4D8CC)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F4)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF1E5)
val surfaceContainerLightMediumContrast = Color(0xFFF9ECDF)
val surfaceContainerHighLightMediumContrast = Color(0xFFF3E6DA)
val surfaceContainerHighestLightMediumContrast = Color(0xFFEDE0D4)

val primaryLightHighContrast = Color(0xFF321E00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF5D3C00)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF2E1F09)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF524027)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF172608)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF364826)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F4)
val onBackgroundLightHighContrast = Color(0xFF201B13)
val surfaceLightHighContrast = Color(0xFFFFF8F4)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF0E0CF)
val onSurfaceVariantLightHighContrast = Color(0xFF2B2318)
val outlineLightHighContrast = Color(0xFF4B4135)
val outlineVariantLightHighContrast = Color(0xFF4B4135)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF362F27)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFE9CF)
val surfaceDimLightHighContrast = Color(0xFFE4D8CC)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F4)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFFF1E5)
val surfaceContainerLightHighContrast = Color(0xFFF9ECDF)
val surfaceContainerHighLightHighContrast = Color(0xFFF3E6DA)
val surfaceContainerHighestLightHighContrast = Color(0xFFEDE0D4)

val primaryDark = Color(0xFFF4BD6F)
val onPrimaryDark = Color(0xFF452B00)
val primaryContainerDark = Color(0xFF633F00)
val onPrimaryContainerDark = Color(0xFFFFDDB3)
val secondaryDark = Color(0xFFDDC2A1)
val onSecondaryDark = Color(0xFF3E2D16)
val secondaryContainerDark = Color(0xFF56442A)
val onSecondaryContainerDark = Color(0xFFFBDEBC)
val tertiaryDark = Color(0xFFB8CEA1)
val onTertiaryDark = Color(0xFF243515)
val tertiaryContainerDark = Color(0xFF3A4C2A)
val onTertiaryContainerDark = Color(0xFFD4EABB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF18120B)
val onBackgroundDark = Color(0xFFEDE0D4)
val surfaceDark = Color(0xFF18120B)
val onSurfaceDark = Color(0xFFEDE0D4)
val surfaceVariantDark = Color(0xFF4F4539)
val onSurfaceVariantDark = Color(0xFFD3C4B4)
val outlineDark = Color(0xFF9C8F80)
val outlineVariantDark = Color(0xFF4F4539)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEDE0D4)
val inverseOnSurfaceDark = Color(0xFF362F27)
val inversePrimaryDark = Color(0xFF805610)
val surfaceDimDark = Color(0xFF18120B)
val surfaceBrightDark = Color(0xFF3F3830)
val surfaceContainerLowestDark = Color(0xFF120D07)
val surfaceContainerLowDark = Color(0xFF201B13)
val surfaceContainerDark = Color(0xFF251F17)
val surfaceContainerHighDark = Color(0xFF2F2921)
val surfaceContainerHighestDark = Color(0xFF3B342B)

val primaryDarkMediumContrast = Color(0xFFF9C172)
val onPrimaryDarkMediumContrast = Color(0xFF221300)
val primaryContainerDarkMediumContrast = Color(0xFFB9883F)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFE2C6A5)
val onSecondaryDarkMediumContrast = Color(0xFF211402)
val secondaryContainerDarkMediumContrast = Color(0xFFA58D6F)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFBCD2A5)
val onTertiaryDarkMediumContrast = Color(0xFF0B1A01)
val tertiaryContainerDarkMediumContrast = Color(0xFF83976E)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF18120B)
val onBackgroundDarkMediumContrast = Color(0xFFEDE0D4)
val surfaceDarkMediumContrast = Color(0xFF18120B)
val onSurfaceDarkMediumContrast = Color(0xFFFFFAF7)
val surfaceVariantDarkMediumContrast = Color(0xFF4F4539)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD7C8B8)
val outlineDarkMediumContrast = Color(0xFFAEA192)
val outlineVariantDarkMediumContrast = Color(0xFF8E8173)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFEDE0D4)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF302921)
val inversePrimaryDarkMediumContrast = Color(0xFF644100)
val surfaceDimDarkMediumContrast = Color(0xFF18120B)
val surfaceBrightDarkMediumContrast = Color(0xFF3F3830)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF120D07)
val surfaceContainerLowDarkMediumContrast = Color(0xFF201B13)
val surfaceContainerDarkMediumContrast = Color(0xFF251F17)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2F2921)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3B342B)

val primaryDarkHighContrast = Color(0xFFFFFAF7)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFF9C172)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFFAF7)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFE2C6A5)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF3FFE2)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFBCD2A5)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF18120B)
val onBackgroundDarkHighContrast = Color(0xFFEDE0D4)
val surfaceDarkHighContrast = Color(0xFF18120B)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4F4539)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFAF7)
val outlineDarkHighContrast = Color(0xFFD7C8B8)
val outlineVariantDarkHighContrast = Color(0xFFD7C8B8)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEDE0D4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF3C2500)
val surfaceDimDarkHighContrast = Color(0xFF18120B)
val surfaceBrightDarkHighContrast = Color(0xFF3F3830)
val surfaceContainerLowestDarkHighContrast = Color(0xFF120D07)
val surfaceContainerLowDarkHighContrast = Color(0xFF201B13)
val surfaceContainerDarkHighContrast = Color(0xFF251F17)
val surfaceContainerHighDarkHighContrast = Color(0xFF2F2921)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3B342B)
