package com.example.reply.ui.theme

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val reply_light_primary= Color(0xFF825500)
val reply_light_on_primary = Color(0xFFFFFFFF)
val reply_light_primary_container = Color(0xFFFFDDAE)
val reply_light_on_primary_container = Color(0xFF2A1800)
val reply_light_secondary = Color(0xFF6F5B40)
val reply_light_on_secondary = Color(0xFFFFFFFF)
val reply_light_secondary_container = Color(0xFFFADEBC)
val reply_light_on_secondary_container = Color(0xFF271904)
val reply_light_tertiary = Color(0xFF516440)
val reply_light_on_tertiary = Color(0xFFFFFFFF)
val reply_light_tertiary_container = Color(0xFFD3EABC)
val reply_light_on_tertiary_container = Color(0xFF102004)
val reply_light_error = Color(0xFFBA1B1B)
val reply_light_error_container = Color(0xFFFFDAD4)
val reply_light_on_error = Color(0xFFFFFFFF)
val reply_light_on_error_container = Color(0xFF410001)
val reply_light_background = Color(0xFFFCFCFC)
val reply_light_on_background = Color(0xFF1F1B16)
val reply_light_surface = Color(0xFFFCFCFC)
val reply_light_on_surface = Color(0xFF1F1B16)
val reply_light_surface_variant = Color(0xFFF0E0CF)
val reply_light_on_surface_variant = Color(0xFF4F4539)
val reply_light_outline = Color(0xFF817567)
val reply_light_inverse_on_surface = Color(0xFFF9EFE6)
val reply_light_inverse_surface = Color(0xFF34302A)
val reply_light_primary_inverse = Color(0xFFFFB945)


val reply_dark_primary = Color(0xFFFFB945)
val reply_dark_on_primary = Color(0xFF452B00)
val reply_dark_primary_container = Color(0xFF624000)
val reply_dark_on_primary_container = Color(0xFFFFDDAE)
val reply_dark_secondary = Color(0xFFDDC3A2)
val reply_dark_on_secondary = Color(0xFF3E2E16)
val reply_dark_secondary_container = Color(0xFF56442B)
val reply_dark_on_secondary_container = Color(0xFFFADEBC)
val reply_dark_tertiary = Color(0xFFB8CEA2)
val reply_dark_on_tertiary = Color(0xFF243516)
val reply_dark_tertiary_container = Color(0xFF3A4C2B)
val reply_dark_on_tertiary_container = Color(0xFFD3EABC)
val reply_dark_error = Color(0xFFFFB4A9)
val reply_dark_error_container = Color(0xFF930006)
val reply_dark_on_error = Color(0xFF680003)
val reply_dark_on_error_container = Color(0xFFFFDAD4)
val reply_dark_background = Color(0xFF1F1B16)
val reply_dark_on_background = Color(0xFFEAE1D9)
val reply_dark_surface = Color(0xFF1F1B16)
val reply_dark_on_surface = Color(0xFFEAE1D9)
val reply_dark_surface_variant = Color(0xFF4F4539)
val reply_dark_on_surface_variant = Color(0xFFD3C4B4)
val reply_dark_outline = Color(0xFF9C8F80)
val reply_dark_inverse_on_surface = Color(0xFF1F1B16)
val reply_dark_inverse_surface = Color(0xFFEAE1D9)
val reply_dark_primary_inverse = Color(0xFF825500)