name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: Build + Test
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [21, 29]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

#      TODO: Cache dependencies using actions/cache

#      TODO: Run Ktlint
#      - name: Ktlint
#        run: ./gradlew ktlint

      - name: Build project
        run: ./gradlew assemble --stacktrace

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace
