name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: Build + Test
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

#      TODO: Cache dependencies using actions/cache

#      TODO: Run Ktlint
#      - name: Ktlint
#        run: ./gradlew ktlint

      - name: Build project
        run: ./gradlew assemble --stacktrace

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 21
          arch: x86_64
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace
