name: Create a task

on:
  issues:
    types: [opened, reopened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: malmstein/github-asana-action@0.4.0
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          asana-project: ${{ secrets.GH_ASANA_ISSUES_PROJECT_ID }}
          action: 'create-issue-task'
