name: Create a task

on:
  issues:
    types: [opened, reopened]

jobs:
  create-asana-task:
    runs-on: ubuntu-latest
    steps:
      - name: Create Asana task
        uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          asana-project: ${{ secrets.GH_ASANA_ISSUES_PROJECT_ID }}
          asana-custom-field: ${{ secrets.GH_ASANA_ISSUES_CUSTOM_FIELD_ID }}
          action: 'create-issue-task'
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Render template
        id: render_template
        uses: chuhlomin/render-template@v1.7
        with:
          template: .github/issue-reply-template.md
          vars: |
            author: ${{ github.event.issue.actor }}

      - name: Add comment
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: ${{ github.event.issue.number }}
          body-path: '.github/issue-reply-template.md'