name: Changes to project files

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Jetcaster/**'
      - 'Jetchat/**'
      - 'JetLagged/**'
      - 'JetNews/**'
      - 'Jetsnack/**'
      - 'Reply/**'
  pull_request:
    paths-ignore:
      - 'Jetcaster/**'
      - 'Jetchat/**'
      - 'JetLagged/**'
      - 'JetNews/**'
      - 'Jetsnack/**'
      - 'Reply/**'

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run a simple check
        run: echo "Running a simple check on files outside sample directories"
