name: Jetsurvey

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Jetsurvey.yaml'
      - 'Jetsurvey/**'
  pull_request:
    paths:
      - '.github/workflows/Jetsurvey.yaml'
      - 'Jetsurvey/**'

jobs:
  build:
    uses: android/compose-samples/.github/workflows/build-sample.yml@main
    with:
      name: Jetsurvey
      path: Jetsurvey
