name: Jetsurvey

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Jetsurvey.yaml'
      - 'Jetsurvey/**'
  pull_request:
    paths:
      - '.github/workflows/Jetsurvey.yaml'
      - 'Jetsurvey/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: android/compose-samples/.github/workflows/build-sample
        with:
          name: Jetsurvey
          path: Jetsurvey
