name: Jetsnack

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Jetsnack.yaml'
      - 'Jetsnack/**'
  pull_request:
    paths:
      - '.github/workflows/Jetsnack.yaml'
      - 'Jetsnack/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: android/compose-samples/.github/workflows/build-sample
        with:
          name: Jetsnack
          path: Jetsnack
