name: Jetsnack

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Jetsnack.yaml'
      - 'Jetsnack/**'
  pull_request:
    paths:
      - '.github/workflows/Jetsnack.yaml'
      - 'Jetsnack/**'
  workflow_dispatch:

jobs:
  build:
    uses: android/compose-samples/.github/workflows/build-sample.yml@main
    with:
      name: Jetsnack
      path: Jetsnack
