name: Owl

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Owl.yaml'
      - 'Owl/**'
  pull_request:
    paths:
      - '.github/workflows/Owl.yaml'
      - 'Owl/**'
  workflow_dispatch:

env:
  SAMPLE_PATH: Owl

jobs:
  build:
    uses: android/compose-samples/.github/workflows/build-sample.yml@main
    with:
      name: Owl
      path: Owl

  test:
    needs: build
    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [23, 26, 29]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate cache key
        run: ./scripts/checksum.sh $SAMPLE_PATH checksum.txt

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace
          working-directory: ${{ env.SAMPLE_PATH }}

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-owl-${{ matrix.api-level }}
          path: ${{ env.SAMPLE_PATH }}/app/build/reports
