name: Create a task

on:
  pull_request_review:
    types: [submitted]

jobs:
  pr-reviewed:
    runs-on: ubuntu-latest
    steps:
      - name: Update Asana task -> PR reviewed
        uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          action: 'pr-reviewed'