name: Build all projects on new version tag
on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

permissions:
  contents: read

env:
  compose_store_password: ${{ secrets.COMPOSE_STORE_PASSWORD }}
  compose_key_alias: ${{ secrets.COMPOSE_KEY_ALIAS }}
  compose_key_password: ${{ secrets.COMPOSE_KEY_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build all projects
        run: ./scripts/gradlew_recursive.sh assembleDebug